#!/usr/bin/env bash

pip3 install requests
pip3 install tqdm
pipe intall datetime
pip3 install selenium
pip3 install selenium.webdriver
pip3 install webdriver_manager
pip3 install selenium.common
pip3 install datetime